### ISSUE TITLE
modification of leaflet qc output code

### ISSUE THREAD

**Issue by einarhjorleifsson** [ices-eg/wg_WGSFD#18]
hi colin
regarding the leaflet map coding comparing 2016 data from 2018 vs 2017 datacall, i.e. `report_leaflet_datacall_comparison.R`:
1) suggest removing the trimming by quantiles, both for the dsar and the sar
2) suggest adding the following lines (indicated in comments below) to the following code snippet:
```
# Merge the data and calculate the difference in the sar value
  d <-
    thisyear %>%
    full_join(lastyear) %>%
    mutate(thisyear = ifelse(is.na(thisyear), 0, thisyear),             # new code
           lastyear = ifelse(is.na(lastyear), 0, lastyear)) %>%         # new code
    mutate(diff = thisyear - lastyear) %>%
    tbl_df()
```
e

**Comment by colinpmillar** [comment]
Looks much better :)
![image](https://user-images.githubusercontent.com/1502848/41382194-01a39cca-6f63-11e8-8da3-012036a71167.png)
@nielshintzen
