### ISSUE TITLE
 VMSdatacall_proposedWorkflow: storeScheme '=' instead of '<-'

### ISSUE THREAD

**Issue by mrska** [ices-eg/wg_WGSFD#24]
Hi

with the newest version of the VMSdatacall_proposedWorkflow I got the error running     
```
storeScheme <-
      expand.grid(
        years = year,
        months = 0,
        weeks = 0,
        analyse.by <- unique(subTacsat[, "LE_GEAR"])
      )

```
Works when I replace '<- unique(...)' with '=unique(...)'. Not sure if this crashes only in my case or maybe someone else had the same problem. Still '=' would be safer in this case.

**Comment by colinpmillar** [comment]
Thank you! I will fix this now

**Comment by mrska** [comment]
Just found, the same here:

```
save(
    tacsatp,
    file <- file.path(outPath, paste0("tacsatActivity", year, ".RData"))
  )
```

**Comment by mrska** [comment]
A few more tiny bugs

- to delete lines 1036 - 1038
`  mutate(
    VE_REF_annonymised = factor(VE_REF
  ) %>%`

- to replace in line 817
`if (!"trip" %in% linkTacsatEflalo) stop("trip must be in linkTacsatEflalo")`
with
`if (!"trip" %in% linkEflaloTacsat) stop("trip must be in linkEflaloTacsat")`

**Comment by colinpmillar** [comment]
Thanks!! commited in:
https://github.com/ices-eg/wg_WGSFD/commit/66d886965c31be65f94504d769539de47f1bcb77

**Comment by mrska** [comment]
One more small thing that may cause some significant errors:
`
  res <-
    aggregate(
      eflalo$dummy,
      by = as.list(eflalo[, c("VE_COU", "VE_REF", "LE_CDAT")]),
      FUN = sum,
      na.rm <- TRUE
    )  
  `

I have no idea why, but when used na.rm <- TRUE, the summed number of rows is wrong (adds 1 to all values). As before works when replaced with na.rm = TRUE
