### ISSUE TITLE
ices datacall 2020 submission data format

### ISSUE THREAD

**Issue by roimartins** [ices-eg/wg_WGSFD#28]
It has been many issues related to the foramt required to upload the data in ICES system. 

@cmspinto and @jepol77  provided following inforamtion: 

- [ ] Submission CSV cant have headers 
- [ ] Submission CSV cant have quotes 

Possible solution to include in the R Script provided by @jepol77 : 

write.table(table1Save, file="myfile.csv", row.names=FALSE, col.names=FALSE, sep=",", quote = F)

**Comment by colinpmillar** [comment]
Hi,  Also because the AnonymousVesselId column is mandatory, the NA needs to be coded as someing... it seems most people have been using "NA", so i suggest removing the, na = "" argumnent in the current code.

**Comment by colinpmillar** [comment]
Different plan - force NA as implemented here: https://github.com/ices-eg/wg_WGSFD/pull/34

to allow other columns to have empty feilds which will be interpreted as NULL

**Comment by roimartins** [comment]
this can be close.  is now discussed in new issues link to SFD discussions
