### ISSUE TITLE
Task for Neil H.

### ISSUE THREAD

**Issue by LaraSalvany** [ices-eg/wg_WGSFD#5]
@neil-ices-dk : check for text updates (Legal scope)
https://community.ices.dk/admin/DataCalls/_layouts/15/WopiFrame.aspx?sourcedoc=/admin/DataCalls/2018%20Data%20calls/VMS%20Data%20Call%202018/VMS.datacall.2018_Draft.docx&action=default

**Comment by neil-ices-dk** [comment]
Delivered; left a note on QC that needs looking at
