### ISSUE TITLE
Task for Colin

### ISSUE THREAD

**Issue by LaraSalvany** [ices-eg/wg_WGSFD#6]
@colinpmillar : updates on Workflow (R script)

https://github.com/ices-eg/VMS-datacall

NB - now located: https://github.com/ices-eg/wg_WGSFD/tree/master/VMS-datacall

**Comment by colinpmillar** [comment]
I have moved the workflow scripts to here:
https://github.com/ices-eg/wg_WGSFD/tree/master/VMS-datacall

and archived the old repository

@LaraSalvany was there anything else needed here?  Did you want me to check through the script to see that it was good to go for the 2018 datacall?
